name: Build

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      acr_name:
        required: true
        type: string
    secrets:
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          # tags: ${{ inputs.acr_name }}/${{ inputs.image_name }}:ci-${{ github.run_id }}
          tags: ${{ inputs.image_name }}:ci-${{ github.run_id }}
      - name: Save Docker image as TAR
        run: docker save ${{ inputs.image_name }}:ci-${{ github.run_id }} -o image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar