name: SAST - CodeQL

on:
  workflow_call:

jobs:
  sast:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3

      - name: Autobuild for CodeQL
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        
      - name: Upload CodeQL report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: codeql-report
          path: codeql-results.sarif