name: Test

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detectando tipo de proyecto
        id: detect
        run: |
          echo "Detectando tipo de proyecto"
          
          if [ -f "package.json" ]; then
            echo "PROJECT_TYPE=nodejs" >> $GITHUB_OUTPUT
          elif [ -f "requirements.txt" ] || [ -f "pyproject.toml" ] || [ -d "app" ]; then
            echo "PROJECT_TYPE=python" >> $GITHUB_OUTPUT
          elif [ -f "pom.xml" ] || [ -f "build.gradle" ]; then
            echo "PROJECT_TYPE=java" >> $GITHUB_OUTPUT
          else
            echo "PROJECT_TYPE=unknown" >> $GITHUB_OUTPUT
          fi

      # --- Setup environments dynamically ---
      - name: Setup Node.js
        if: steps.detect.outputs.PROJECT_TYPE == 'nodejs'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Python
        if: steps.detect.outputs.PROJECT_TYPE == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Setup Java
        if: steps.detect.outputs.PROJECT_TYPE == 'java'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      # --- Run Unit Tests depending on type ---
      - name: Run unit tests
        run: |
          case "${{ steps.detect.outputs.PROJECT_TYPE }}" in
            "nodejs")
              echo "Corriendo Node.js tests..."
              npm ci
              npm run test --if-present || echo "No hay test"
              ;;
            "python")
              echo "Corriendo Python tests..."
              python -m pip install --upgrade pip
              [ -f "requirements.txt" ] && pip install -r requirements.txt
              [ -f "requirements-dev.txt" ] && pip install -r requirements-dev.txt
              pytest --maxfail=1 --disable-warnings -v || echo "No hay test"
              ;;
            "java")
              echo "Running Java tests..."
              if [ -f "gradlew" ]; then
                ./gradlew test --info || echo "No hay test"
              elif [ -f "mvnw" ]; then
                ./mvnw test || echo "No hay test"
              else
                echo ""
              fi
              ;;
            *)
              echo "No hay test para el tipo de proyecto: ${{ steps.detect.outputs.PROJECT_TYPE }}"
              ;;
          esac